* Recipi
  [[https://travis-ci.org/shellhead/recipi.svg?branch=master]]

  Recipi is a personal web server to store recipes and generate shopping lists
  with Wunderlist.

  I started this project to become more familiar with a variety of
  technologies. I've tried to keep notes from my trials and tribulations
  throughout the project. You can find these notes in =docs/README.org=.

* Features
  As this project is still in it's infancy, there aren't many features. Below
  is a list of hopeful functionality.

  - Store recipes.
  - Search for recipes based on ingredients, cuisine, cooking time, etc.
  - Generate a Wunderlist shopping list with all the required ingredients.
  - Notify users when previously purchased ingredients may go bad.
  - Search social networks (Reddit and Twitter) for recipes to suggest adding.
  - More to come!

* Usage
  Ensure you have [[http://leiningen.org/][leiningen]] and Java installed.

  #+BEGIN_SRC sh
  lein ring server-headless
  #+END_SRC

* Documentation
  After the server is started, point your browser at
  =http://localhost:3000/swagger= for some pretty Swagger documentation.

* Test
  Using [[https://github.com/marick/Midje][midje]] to test. If tests fail, you may have to add the following to
  =~/.lein/profiles.clj=.

  #+BEGIN_SRC clojure
  {:user {:plugins [[lein-midje "3.1.3"]]}}
  #+END_SRC

  To kick off the tests (and keep the session open to rerun tests), run the
  following.

  #+BEGIN_SRC sh
  lein midje :autotest
  #+END_SRC
